### ISSUE TITLE
Compiling Bot project with Microsoft Visual Studio 2013 Express, atlbase.h and atlstr.h are missing

### ISSUE THREAD

**Issue by donaldm** [GET-TUDA-CHOPPA/SpelunkBots#3]
Hello,

I am trying to compile the Bot project on Microsoft Visual Studio 2013 Express. The compile was complaining because the atlbase.h and atlstr.h headers were missing, and I removed these headers and the project compiled fine.

Are these headers necessary? It seems that these might be headers used for creating drivers? I am not sure these headers are necessary for creating a DLL as I have not had to use them before (and I have created GML DLLs before).

The offending lines are in stdafx.h on line 14 and 15.

Any thoughts?

**Comment by Poliziano** [comment]
Hello donaldm,

The Bot DLL should compile without needing to make any changes. I usually use Visual Studio 2013 Community, but I've just downloaded the Express edition and everything has compiled without any complaints, so I'm not sure what to suggest.

If you can compile without these headers included then I don't see why it would make any differences to the DLLs functionality. I'll have a look in to this issue to see if I can find anything, but right now the easiest solution may be to just removed the headers causing the problem.

**Comment by Poliziano** [comment]
Update: A quick search leads me to believe it is an issue with the ATL not being included with Visual Studio 2013 Express. I presume the reason it worked for me was because I have other versions of Visual Studios which includes the ATL.

If you don't have any other version of Visual Studio installed could I suggest installing Visual Studio 2013 Community, which includes the ATL, and try using that if that is not too much of a problem for you:

https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx

**Comment by donaldm** [comment]
Hello Poliziano,

Thank you for the information on Visual Studio Community Edition. This edition seems like it has a number of improvements over the express edition that I was using.

I guess though my question still stands that if the code is compiling without the ATL headers being included, is their inclusion necessary? I was just wondering if they have a purpose or not.

Thank you for your time.

**Comment by Poliziano** [comment]
Hello,

No, they do not have a purpose. atlbase.h and atlstr.h were added to the precompiled header when the project was created and we hadn't removed any headers we didn't need. We had a meeting yesterday and this issue was brought up and we've decided to remove any headers we don't need, which includes atlbase.h and atlstr.h.

I hope this answers your question, and if you have any more issues or queries don't hesitate to ask - we can't make the API better without feedback!
